package DJKMitglieder::Model::DB;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config(
    schema_class => 'DJKMitglieder::Schema',
    connect_info => {
        dsn => 'dbi:mysql:djkmitglieder',
        user => 'verwaltung',
        password => 'AnderKohlstatt1',
        AutoCommit => q{1},
    }
);

=head1 NAME

DJKMitglieder::Model::DB - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<DJKMitglieder>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<DJKMitglieder::Schema>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.59

=head1 AUTHOR

root

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
